package com.factory.ml.controller;

import javafx.fxml.FXML;
import javafx.scene.web.WebView;
import javafx.scene.control.Label;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 * Controller for the Analysis Report view in the Factory ML GUI.
 * 
 * This controller displays HTML-based analysis reports generated by the
 * Python training pipeline. Reports include model metrics, feature importance,
 * and other analytical visualizations.
 * 
 * <p>Project Context:
 * Part of the factory-ml-offline-system JavaFX GUI. Provides a WebView-based
 * interface for viewing generated HTML reports.
 */
public class AnalysisReportController {

    @FXML
    private WebView reportWebView;

    @FXML
    private Label statusLabel;

    /**
     * Loads an HTML report from the specified file path.
     * 
     * Reads the HTML report file, loads it into the WebView, and updates
     * the status label. Handles file not found and I/O errors gracefully.
     * 
     * @param reportPath Absolute path to the HTML report file
     */
    public void loadReport(String reportPath) {
        try {
            File reportFile = new File(reportPath);
            if (reportFile.exists()) {
                String content = new String(Files.readAllBytes(Paths.get(reportPath)));
                reportWebView.getEngine().loadContent(content);
                statusLabel.setText("Report loaded successfully.");
            } else {
                statusLabel.setText("Report file not found.");
            }
        } catch (Exception e) {
            statusLabel.setText("Error loading report: " + e.getMessage());
        }
    }
}